<?php

 $modulePath = drupal_get_path('module', 'aae_data');
 include_once $modulePath . '/aae_data_helper.php';

/** @function hook_cron()
*
* Cronjob, der von Drupal automatisch aufgerufen wird.
*/
function aae_data_cron() {
  //....
}

function aae_data_user_logout($account) {

  // Funktioniert nicht, weil Drupal Sessions löscht :(

  if (session_status() == PHP_SESSION_NONE) session_start();

  $_SESSION['sysmsg'][] = 'Ausgeloggt. Komm` bald wieder!';
}

/**
 * @function hook_menu()
 *
 * Verlinkt URL-Pfade auf die entsprechende Funktion.
 */
function aae_data_menu() {
  $items = array();
  //Menuitem "Akteure"
  $items['Akteure'] = array(
    'title' => 'Akteure',
    'page callback' => 'akteure_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
  );

  //Menuitem "Akteurformular"
  $items['Akteurformular'] = array(
    'title' => 'Akteurformular',
    'page callback' => 'akteurformular_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
  );

  //Menuitem "Akteurprofil"
  $items['Akteurprofil/%'] = array(
    'title' => '',
    'page callback' => 'akteurprofil_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
  );

  //Menuitem "Akteuredit"
  $items['Akteuredit/%'] = array(
    'title' => '',
    'page callback' => 'akteuredit_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
  );

  //Menuitem "Akteurloeschen"
  $items['Akteurloeschen/%'] = array(
    'title' => '',
    'page callback' => 'akteurloeschen_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
  );

  //Menuitem "Events"
  $items['Events'] = array(
    'title' => 'Events',
    'page callback' => 'events_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
  );

  //Menuitem "Eventprofil"
  $items['Eventprofil/%'] = array(
    'title' => '',
    'page callback' => 'eventprofil_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
  );

  //Menuitem "Eventloeschen"
  $items['Eventloeschen/%'] = array(
    'title' => '',
    'page callback' => 'eventloeschen_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
  );

  //Menuitem "Eventedit"
  $items['Eventedit/%'] = array(
    'title' => '',
    'page callback' => 'eventedit_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
  );

  //Menuitem "Eventformular"
  $items['Eventformular'] = array(
    'title' => 'Eventformular',
    'page callback' => 'eventformular_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
  );

  //Menuitem "Tag"
  $items['ics_download/%'] = array(
    'title' => '',
    'page callback' => 'tag_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
  );

  // Fetch AJAX-requests
  $items['ajax/%'] = array(
    'title' => 'ajax request',
    'page callback' => 'ajax_requests',
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Baut die Seite fuer die Tagansicht des Kalenders
 */

function tag_page() {

  $modulePath = drupal_get_path('module', 'aae_data');
  include $modulePath . '/tag.php';

  $path = current_path();
  $path_alias = drupal_lookup_path('alias', $path);

  return $profileHTML;

}

/**
 * Baut die Seite fuer die Akteurliste
 */
function akteure_page() {
  $modulePath = drupal_get_path('module', 'aae_data');
  include $modulePath . '/akteure.php';

  $akteur = new akteure();
  return $akteur->run();
}

/**
 * Baut die Seite fuer das Akteurformular
 */
function akteurformular_page() {
  $modulePath = drupal_get_path('module', 'aae_data');
  include $modulePath . '/akteurformular.php';

  $akteur = new akteurformular();

  return $akteur->run();
}

/**
 * Baut die Seite fuer das Akteurprofil
 */
function akteurprofil_page() {
  $modulePath = drupal_get_path('module', 'aae_data');
  include $modulePath . '/akteurprofil.php';

  $akteurprofil = new aae_akteurprofil();

  return $akteurprofil->run();
}

/**
 * Baut die Seite fuer den Akteuredit
 */
function akteuredit_page($aid = 0) {
  $modulePath = drupal_get_path('module', 'aae_data');
  include $modulePath . '/akteurformular.php';

  $akteur = new akteurformular('update');

  $path = current_path();
  $path_alias = drupal_lookup_path('alias', $path);

  return $akteur->run();
}

/**
 * Baut die Seite fuer das Eventloeschen
 */
function akteurloeschen_page($eid=0) {
  $modulePath = drupal_get_path('module', 'aae_data');
  include $modulePath . '/akteurloeschen.php';

  $path = current_path();
  $path_alias = drupal_lookup_path('alias', $path);

  return $profileHTML;
}

/**
 * Baut die Seite fuer die Events
 */
function events_page() {
  $modulePath = drupal_get_path('module', 'aae_data');
  include $modulePath . '/events.php';

  $event = new events();
  return $event->run();
}

/**
 * Baut die Seite fuer das Eventprofil
 */
function eventprofil_page() {
  $modulePath = drupal_get_path('module', 'aae_data');
  include $modulePath . '/eventprofil.php';

  $eventprofil = new aae_eventprofil();

  return $eventprofil->run();
}

/**
 * Baut die Seite fuer das Eventloeschen
 */
function eventloeschen_page($eid = 0) {
  $modulePath = drupal_get_path('module', 'aae_data');
  include $modulePath . '/eventloeschen.php';

  $path = current_path();
  $path_alias = drupal_lookup_path('alias', $path);

  return $profileHTML;
}

/**
 * Baut die Seite fuer das Eventedit
 */
function eventedit_page($aid = 0) {

  $modulePath = drupal_get_path('module', 'aae_data');
  include $modulePath . '/eventformular.php';

  $event = new eventformular('update');

  $path = current_path();
  $path_alias = drupal_lookup_path('alias', $path);

  return $event->run();
}

/**
 * Baut die Seite fuer das Eventformular
 */
function eventformular_page() {

  $modulePath = drupal_get_path('module', 'aae_data');
  include $modulePath . '/eventformular.php';

  $event = new eventformular();

  $path = current_path();
  $path_alias = drupal_lookup_path('alias', $path);

  return $event->run();
}

/**
 * Gibt ajax-request's an entsprechende Klasse/Funktion weiter
 */

function ajax_requests($id) {

  $modulePath = drupal_get_path('module', 'aae_data');
  include $modulePath . '/aae_data_ajax_requests.php';

  $request = new aae_data_ajax_requests();

  $path = current_path();
  $explodedpath = explode("/", $path);
  $function_called = $request->clearContent($explodedpath[1]);

  switch($function_called) {

   case ('getAkteurKontakt') :
    $request->getAkteurKontakt($id);
   break;

   case ('getAkteurAdresse') :
    $request->getAkteurAdresse($id);
   break;

   case ('getKalender') :
    $request->getKalender();
   break;

   default :
    // U mad? Unbekannter Funktionsaufruf, weg damit...
    exit();
   break;

  }
 }

/**
 * Funktion zum Einlesen aller Stadtteile
 * Wird einmalig aufgerufen in aae_data_install.php
 */
function insert_bezirke() {
  $bezirke = array(
    'Zentrum (Mitte)',
    'Zentrum-Ost (Mitte)',
    'Zentrum-Südost (Mitte)',
    'Seeburgviertel (Mitte)',
    'Zentrum-Süd (Mitte)',
    'Musikviertel (Mitte)',
    'Zentrum-West (Mitte)',
    'Bachviertel (Mitte)',
    'Zentrum-Nordwest (Mitte)',
    'Waldstraßenviertel (Mitte)',
    'Zentrum-Nord (Mitte)',
    'Schönefeld-Abtnaundorf (Nordost)',
    'Schönefeld-Ost (Nordost)',
    'Schönefeld (Nordost)',
    'Mockau-Süd (Nordost)',
    'Mockau-Nord (Nordost)',
    'Mockau (Nordost)',
    'Thekla (Nordost)',
    'Plaußig-Portitz (Nordost)',
    'Neustadt-Neuschönefeld (Ost)',
    'Volkmarsdorf (Ost)',
    'Anger-Crottendorf (Ost)',
    'Sellerhausen-Stünz (Ost)',
    'Paunsdorf (Ost)',
    'Heiterblick (Ost)',
    'Mölkau (Ost)',
    'Engelsdorf (Ost)',
    'Baalsdorf (Ost)',
    'Althen-Kleinpösna (Ost)',
    'Reudnitz-Thonberg (Südost)',
    'Stötteritz (Südost)',
    'Probstheida (Südost)',
    'Meusdorf (Südost)',
    'Liebertwolkwitz (Südost)',
    'Holzhausen (Südost)',
    'Südvorstadt (Süd)',
    'Connewitz (Süd)',
    'Marienbrunn (Süd)',
    'Lößnig (Süd)',
    'Dölitz-Dösen (Süd)',
    'Schleußig (Südwest)',
    'Plagwitz (Südwest)',
    'Kleinzschocher (Südwest)',
    'Großzschocher (Südwest)',
    'Knautkleeberg-Knauthain (Südwest)',
    'Hartmannsdorf-Knautnaundorf (Südwest)',
    'Schönau (West)',
    'Grünau-Ost (West)',
    'Grünau-Mitte (West)',
    'Grünau-Siedlung (West)',
    'Lausen-Grünau (West)',
    'Grünau-Nord (West)',
    'Grünau (West)',
    'Miltitz (West)',
    'Lindenau (Alt-West)',
    'Altlindenau (Alt-West)',
    'Neulindenau (Alt-West)',
    'Leutzsch (Alt-West)',
    'Böhlitz-Ehrenberg (Alt-West)',
    'Burghausen-Rückmarsdorf (Alt-West)',
    'Möckern (Nordwest)',
    'Wahren (Nordwest)',
    'Lützschena-Stahmeln (Nordwest)',
    'Lindenthal (Nordwest)',
    'Gohlis-Süd (Nord)',
    'Gohlis-Mitte (Nord)',
    'Gohlis-Nord (Nord)',
    'Gohlis (Nord)',
    'Eutritzsch (Nord)',
    'Seehausen (Nord)',
    'Wiederitzsch (Nord)',
  );

  $i = 0;
  while ($i < count($bezirke)) {
	$insert_bezirke = db_insert("aae_data_bezirke")
      ->fields(array(
        'bezirksname' => $bezirke[$i],
	  ))
	  ->execute();
	$i++;
  }
  return $insert_bezirke;
}
