<?php

/**
 * Updates Drupal to be way ruther.
 * @TODO Aktiviere diese Funktion nur, wenn sich Drupal im
 * Development-Modus befindet.
 */

if (drupal_is_front_page()) {
  $GLOBALS['conf']['cache'] = FALSE;
}

/** @function hook_cron()
*
* Cronjob, der von Drupal automatisch aufgerufen wird.
* Updated die LOData.js Maps-Koordinaten-Datei
*/

function aae_data_cron() {
  //....
}


/**
 * @function hook_menu()
 *
 * Verlinkt URL-Pfade auf die entsprechende Funktion.
 */

function aae_data_menu() {
  $items = array();
  //Menuitem "Akteure"
  $items['Akteure'] = array(
    'title' => 'Akteure',
    'page callback' => 'akteure_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
  );

  //Menuitem "Akteurformular"
  $items['Akteurformular'] = array(
    'title' => 'Akteurformular',
    'page callback' => 'akteurformular_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
  );

  //Menuitem "Akteurprofil"
  $items['Akteurprofil/%'] = array(
    'title' => '',
    'page callback' => 'akteurprofil_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
  );

  //Menuitem "Akteuredit"
  $items['Akteuredit/%'] = array(
    'title' => '',
    'page callback' => 'akteuredit_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
  );

  //Menuitem "Events"
  $items['Events'] = array(
    'title' => 'Events',
    'page callback' => 'events_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
  );

  //Menuitem "Eventprofil"
  $items['Eventprofil/%'] = array(
    'title' => '',
    'page callback' => 'eventprofil_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
  );

  //Menuitem "Eventloeschen"
  $items['Eventloeschen/%'] = array(
    'title' => '',
    'page callback' => 'eventloeschen_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
  );

  //Menuitem "Eventedit"
  $items['Eventedit/%'] = array(
    'title' => '',
    'page callback' => 'eventedit_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
  );

  //Menuitem "Eventformular"
  $items['Eventformular'] = array(
    'title' => 'Eventformular',
    'page callback' => 'eventformular_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Builds page for Akteurliste
 */
function akteure_page() {
  $modulePath = drupal_get_path('module', 'aae_data');
  include $modulePath . '/akteure.php';

  $path = current_path();
  $path_alias = drupal_lookup_path('alias',$path);

  return $profileHTML;
}
/**
 * Builds page for Akteurformular
 */
function akteurformular_page() {
  $modulePath = drupal_get_path('module', 'aae_data');
  include $modulePath . '/akteurformular.php';

  $path = current_path();
  $path_alias = drupal_lookup_path('alias',$path);

  return $profileHTML;
}
/**
 * Builds page for Akteurprofil
 */
function akteurprofil_page($aid=0) {
  $modulePath = drupal_get_path('module', 'aae_data');
  include $modulePath . '/akteurprofil.php';

  $path = current_path();
  $path_alias = drupal_lookup_path('alias',$path);

  return $profileHTML;
}
/**
 * Builds page for Akteuredit
 */
function akteuredit_page($aid=0) {
  $modulePath = drupal_get_path('module', 'aae_data');
  include $modulePath . '/akteuredit.php';

  $path = current_path();
  $path_alias = drupal_lookup_path('alias',$path);

  return $profileHTML;
}
/**
 * Builds page for Events
 */
function events_page() {
  $modulePath = drupal_get_path('module', 'aae_data');
  include $modulePath . '/events.php';

  $path = current_path();
  $path_alias = drupal_lookup_path('alias',$path);

  return $profileHTML;
}
/**
 * Builds page for Eventprofil
 */
function eventprofil_page($eid=0) {
  $modulePath = drupal_get_path('module', 'aae_data');
  include $modulePath . '/eventprofil.php';

  $path = current_path();
  $path_alias = drupal_lookup_path('alias',$path);

  return $profileHTML;
}
/**
 * Builds page for Eventloeschen
 */
function eventloeschen_page($eid=0) {
  $modulePath = drupal_get_path('module', 'aae_data');
  include $modulePath . '/eventloeschen.php';

  $path = current_path();
  $path_alias = drupal_lookup_path('alias',$path);

  return $profileHTML;
}
/**
 * Builds page for Eventedit
 */
function eventedit_page($aid=0) {
  $modulePath = drupal_get_path('module', 'aae_data');
  include $modulePath . '/eventedit.php';

  $path = current_path();
  $path_alias = drupal_lookup_path('alias',$path);

  return $profileHTML;
}
/**
 * Builds page for Eventformular
 */
function eventformular_page() {
  $modulePath = drupal_get_path('module', 'aae_data');
  include $modulePath . '/eventformular.php';

  $path = current_path();
  $path_alias = drupal_lookup_path('alias',$path);

  return $profileHTML;
}