<?php

if (drupal_is_front_page()) {
  $GLOBALS['conf']['cache'] = FALSE;
}


/**
 * Creates the Künstler Menu item on the left sidebar.
 * Additional, it adds some tabs
 */
function kuenstler_menu() {
    
    //adding a menu item called "Tollstes Plugin Eva"
    $items['kuenstler'] = array(
            'title' => 'E.V. A Künstler',
            'page callback' => '_profile_menu_page',
            'page arguments' => array(t('Statistics')),
            'access callback' => TRUE,
    );
    //Adding a tab called "Holder" to the page called by above defined menu item
    $items["kuenstler/menu/profile"] = array(
                    'type' => MENU_DEFAULT_LOCAL_TASK,
                    'title' => 'Profile',
                    'page callback' => '_profile_menu_page',
                    'access callback' => TRUE,
                    'weight' => 1
    );
    //Adding a tab called "Geolocation" to the page called by above defined menu item
    $items["kuenstler/menu/Statistics"] = array(
                    'type' => MENU_LOCAL_TASK,
                    'title' => 'Statistics',
                    'page callback' => '_statistic_menu_page',
                    'access callback' => TRUE,
                    'weight' => 2
    );
    $items["kuenstler/menu/Friendpage"] = array(
                    'type' => MENU_LOCAL_TASK,
                    'title' => 'Friendpage',
                    'page callback' => '_friendpage_menu_page',
                    'access callback' => TRUE,
                    'weight' => 3
    );
	

  return $items;
}

/**
 * Builds page for profile view and settings
 */
function _profile_menu_page() {
    drupal_add_css("sites/all/modules/kuenstler/kuenstler.css");
    $modulePath = drupal_get_path('module', 'kuenstler');
    include $modulePath . '/templates/profile/profilePage.php';
    
    $path = current_path();
    $path_alias = drupal_lookup_path('alias',$path);
    
    return $profileHTML;
}

/**
 * Builds page for the Google Map
 */
function _statistic_menu_page() {

    drupal_add_css("sites/all/modules/kuenstler/kuenstler.css");
    $modulePath = drupal_get_path('module', 'kuenstler');
    include $modulePath . '/templates/statistics/statisticsPage.php'; 


    return $statisticsHTMLMap;
}

function _friendpage_menu_page() {
    
    $modulePath = drupal_get_path('module', 'kuenstler');
    include $modulePath . '/templates/friends/friendPage.php';
    
    return $friendHTML;
}
